[book]
authors = ["ashutosh jain"]
language = "en"
multilingual = false
src = "src"
title = "Vaidik Ceremonies"
description = " A modern perspective on Vaidik Ceremonies"

[output.html]
theme = "src/theme"
git-repository-url = "https://github.com/ashutoshmjain/cermonies"
cname = "ceremonies.shutri.com"
edit-url-template = "https://github.com/ashutoshmjain/cermonies/edit/main/{path}"
no-section-label = true

[output.html.print]
enable = true    # include support for printable output


